# -*- coding: utf-8 -*-
"""Dever-01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/167lcmeaCN_fa5unN4VpCIuE0I_5V5JBO
"""

# Importar os módulos do sistema operacional
import os
import locale

# Instalar pt_BR
!/usr/share/locales/install-language-pack pt_BR
!dpkg-reconfigure locales pt_BR

# Reiniciar o processo Python
os.kill(os.getpid(), 9)

import pandas as pd

# Criando o arquivo CSV com 5 entradas
dados = [
    ["Pablo Coelho", "01/26/1974", "2025/02/17", "20:30"],
    ["Mariana Ferreira", "04/26/1995", "2025/02/17", "20:31"],
    ["Lucas Andrade", "12/15/1988", "2025/02/17", "20:32"],
    ["Fernanda Souza", "07/03/2000", "2025/02/17", "20:33"],
    ["Rafael Lima", "09/08/1992", "2025/02/17", "20:34"]
]

df = pd.DataFrame(dados, columns=["nome", "dataNasc", "dataCadastrado", "horaCadastro"])
df.to_csv("dados.csv", index=False)

# Lendo o arquivo CSV
df = pd.read_csv("dados.csv")

# Solicitando ao usuário o número do registro
n = int(input("Digite o número do registro (0 a 4): "))

if 0 <= n < len(df):
    nome = df.loc[n, "nome"]
    data_nasc = pd.to_datetime(df.loc[n, "dataNasc"], format="%m/%d/%Y").strftime("%d/%m/%Y")
    data_cadastro = pd.to_datetime(df.loc[n, "dataCadastrado"], format="%Y/%m/%d").strftime("%d/%m/%Y")
    hora_cadastro = df.loc[n, "horaCadastro"]

    print(f"Registro {n}: Nome: {nome}; Data de nascimento: {data_nasc}; Data de cadastro: {data_cadastro} às {hora_cadastro} horas")
else:
    print("Registro inválido!")